//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LanMonitor.FotService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SchedulePackage", Namespace="http://schemas.datacontract.org/2004/07/Fot.Admin.Models")]
    [System.SerializableAttribute()]
    public partial class SchedulePackage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<LanMonitor.FotService.AssessmentBundleViewModel> AssessmentListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DownloadDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsDoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<LanMonitor.FotService.TestScheduleViewModel> ScheduleListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<LanMonitor.FotService.SupportStaffViewModel> StaffListField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<LanMonitor.FotService.AssessmentBundleViewModel> AssessmentList {
            get {
                return this.AssessmentListField;
            }
            set {
                if ((object.ReferenceEquals(this.AssessmentListField, value) != true)) {
                    this.AssessmentListField = value;
                    this.RaisePropertyChanged("AssessmentList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DownloadDate {
            get {
                return this.DownloadDateField;
            }
            set {
                if ((this.DownloadDateField.Equals(value) != true)) {
                    this.DownloadDateField = value;
                    this.RaisePropertyChanged("DownloadDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsDone {
            get {
                return this.IsDoneField;
            }
            set {
                if ((this.IsDoneField.Equals(value) != true)) {
                    this.IsDoneField = value;
                    this.RaisePropertyChanged("IsDone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<LanMonitor.FotService.TestScheduleViewModel> ScheduleList {
            get {
                return this.ScheduleListField;
            }
            set {
                if ((object.ReferenceEquals(this.ScheduleListField, value) != true)) {
                    this.ScheduleListField = value;
                    this.RaisePropertyChanged("ScheduleList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<LanMonitor.FotService.SupportStaffViewModel> StaffList {
            get {
                return this.StaffListField;
            }
            set {
                if ((object.ReferenceEquals(this.StaffListField, value) != true)) {
                    this.StaffListField = value;
                    this.RaisePropertyChanged("StaffList");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AssessmentBundleViewModel", Namespace="http://schemas.datacontract.org/2004/07/Fot.Admin.Models")]
    [System.SerializableAttribute()]
    public partial class AssessmentBundleViewModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BundleIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BundleId {
            get {
                return this.BundleIdField;
            }
            set {
                if ((this.BundleIdField.Equals(value) != true)) {
                    this.BundleIdField = value;
                    this.RaisePropertyChanged("BundleId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TestScheduleViewModel", Namespace="http://schemas.datacontract.org/2004/07/Fot.Admin.Models")]
    [System.SerializableAttribute()]
    public partial class TestScheduleViewModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BundleIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CampaignIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CandidateIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MobileNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SessionIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ShowFeedbackField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BundleId {
            get {
                return this.BundleIdField;
            }
            set {
                if ((this.BundleIdField.Equals(value) != true)) {
                    this.BundleIdField = value;
                    this.RaisePropertyChanged("BundleId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CampaignId {
            get {
                return this.CampaignIdField;
            }
            set {
                if ((this.CampaignIdField.Equals(value) != true)) {
                    this.CampaignIdField = value;
                    this.RaisePropertyChanged("CampaignId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CandidateId {
            get {
                return this.CandidateIdField;
            }
            set {
                if ((this.CandidateIdField.Equals(value) != true)) {
                    this.CandidateIdField = value;
                    this.RaisePropertyChanged("CandidateId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Firstname {
            get {
                return this.FirstnameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstnameField, value) != true)) {
                    this.FirstnameField = value;
                    this.RaisePropertyChanged("Firstname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Lastname {
            get {
                return this.LastnameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastnameField, value) != true)) {
                    this.LastnameField = value;
                    this.RaisePropertyChanged("Lastname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MobileNo {
            get {
                return this.MobileNoField;
            }
            set {
                if ((object.ReferenceEquals(this.MobileNoField, value) != true)) {
                    this.MobileNoField = value;
                    this.RaisePropertyChanged("MobileNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SessionId {
            get {
                return this.SessionIdField;
            }
            set {
                if ((this.SessionIdField.Equals(value) != true)) {
                    this.SessionIdField = value;
                    this.RaisePropertyChanged("SessionId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ShowFeedback {
            get {
                return this.ShowFeedbackField;
            }
            set {
                if ((this.ShowFeedbackField.Equals(value) != true)) {
                    this.ShowFeedbackField = value;
                    this.RaisePropertyChanged("ShowFeedback");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SupportStaffViewModel", Namespace="http://schemas.datacontract.org/2004/07/Fot.Admin.Models")]
    [System.SerializableAttribute()]
    public partial class SupportStaffViewModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsCaptureAdminField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsSupportStaffField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Firstname {
            get {
                return this.FirstnameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstnameField, value) != true)) {
                    this.FirstnameField = value;
                    this.RaisePropertyChanged("Firstname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsCaptureAdmin {
            get {
                return this.IsCaptureAdminField;
            }
            set {
                if ((this.IsCaptureAdminField.Equals(value) != true)) {
                    this.IsCaptureAdminField = value;
                    this.RaisePropertyChanged("IsCaptureAdmin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSupportStaff {
            get {
                return this.IsSupportStaffField;
            }
            set {
                if ((this.IsSupportStaffField.Equals(value) != true)) {
                    this.IsSupportStaffField = value;
                    this.RaisePropertyChanged("IsSupportStaff");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Lastname {
            get {
                return this.LastnameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastnameField, value) != true)) {
                    this.LastnameField = value;
                    this.RaisePropertyChanged("Lastname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BundlePackage", Namespace="http://schemas.datacontract.org/2004/07/Fot.Admin.Models")]
    [System.SerializableAttribute()]
    public partial class BundlePackage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] BundleDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BundleIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BundleNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DownloadDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsDoneField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] BundleData {
            get {
                return this.BundleDataField;
            }
            set {
                if ((object.ReferenceEquals(this.BundleDataField, value) != true)) {
                    this.BundleDataField = value;
                    this.RaisePropertyChanged("BundleData");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BundleId {
            get {
                return this.BundleIdField;
            }
            set {
                if ((this.BundleIdField.Equals(value) != true)) {
                    this.BundleIdField = value;
                    this.RaisePropertyChanged("BundleId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BundleName {
            get {
                return this.BundleNameField;
            }
            set {
                if ((object.ReferenceEquals(this.BundleNameField, value) != true)) {
                    this.BundleNameField = value;
                    this.RaisePropertyChanged("BundleName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DownloadDate {
            get {
                return this.DownloadDateField;
            }
            set {
                if ((this.DownloadDateField.Equals(value) != true)) {
                    this.DownloadDateField = value;
                    this.RaisePropertyChanged("DownloadDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsDone {
            get {
                return this.IsDoneField;
            }
            set {
                if ((this.IsDoneField.Equals(value) != true)) {
                    this.IsDoneField = value;
                    this.RaisePropertyChanged("IsDone");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultUpdateModel", Namespace="http://schemas.datacontract.org/2004/07/Fot.Admin.Models")]
    [System.SerializableAttribute()]
    public partial class ResultUpdateModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CampaignIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CandidateIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] CandidatePhotoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LanMonitor.FotService.FeedbackModel FeedbackField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> PhotoCapturedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<LanMonitor.FotService.ResultEntryModel> ResultsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SessionIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime TestEndTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime TestStartTimeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CampaignId {
            get {
                return this.CampaignIdField;
            }
            set {
                if ((this.CampaignIdField.Equals(value) != true)) {
                    this.CampaignIdField = value;
                    this.RaisePropertyChanged("CampaignId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CandidateId {
            get {
                return this.CandidateIdField;
            }
            set {
                if ((this.CandidateIdField.Equals(value) != true)) {
                    this.CandidateIdField = value;
                    this.RaisePropertyChanged("CandidateId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] CandidatePhoto {
            get {
                return this.CandidatePhotoField;
            }
            set {
                if ((object.ReferenceEquals(this.CandidatePhotoField, value) != true)) {
                    this.CandidatePhotoField = value;
                    this.RaisePropertyChanged("CandidatePhoto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LanMonitor.FotService.FeedbackModel Feedback {
            get {
                return this.FeedbackField;
            }
            set {
                if ((object.ReferenceEquals(this.FeedbackField, value) != true)) {
                    this.FeedbackField = value;
                    this.RaisePropertyChanged("Feedback");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> PhotoCapturedBy {
            get {
                return this.PhotoCapturedByField;
            }
            set {
                if ((this.PhotoCapturedByField.Equals(value) != true)) {
                    this.PhotoCapturedByField = value;
                    this.RaisePropertyChanged("PhotoCapturedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<LanMonitor.FotService.ResultEntryModel> Results {
            get {
                return this.ResultsField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultsField, value) != true)) {
                    this.ResultsField = value;
                    this.RaisePropertyChanged("Results");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SessionId {
            get {
                return this.SessionIdField;
            }
            set {
                if ((this.SessionIdField.Equals(value) != true)) {
                    this.SessionIdField = value;
                    this.RaisePropertyChanged("SessionId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime TestEndTime {
            get {
                return this.TestEndTimeField;
            }
            set {
                if ((this.TestEndTimeField.Equals(value) != true)) {
                    this.TestEndTimeField = value;
                    this.RaisePropertyChanged("TestEndTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime TestStartTime {
            get {
                return this.TestStartTimeField;
            }
            set {
                if ((this.TestStartTimeField.Equals(value) != true)) {
                    this.TestStartTimeField = value;
                    this.RaisePropertyChanged("TestStartTime");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FeedbackModel", Namespace="http://schemas.datacontract.org/2004/07/Fot.Admin.Models")]
    [System.SerializableAttribute()]
    public partial class FeedbackModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> BriefingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CommentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> DirectionsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> OverallField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ProfessionalismField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> RegistrationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> SatisfactoryAreaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> StartTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> UnsatisfactoryAreaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> WaitTimeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Briefing {
            get {
                return this.BriefingField;
            }
            set {
                if ((this.BriefingField.Equals(value) != true)) {
                    this.BriefingField = value;
                    this.RaisePropertyChanged("Briefing");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Comments {
            get {
                return this.CommentsField;
            }
            set {
                if ((object.ReferenceEquals(this.CommentsField, value) != true)) {
                    this.CommentsField = value;
                    this.RaisePropertyChanged("Comments");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Directions {
            get {
                return this.DirectionsField;
            }
            set {
                if ((this.DirectionsField.Equals(value) != true)) {
                    this.DirectionsField = value;
                    this.RaisePropertyChanged("Directions");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Overall {
            get {
                return this.OverallField;
            }
            set {
                if ((this.OverallField.Equals(value) != true)) {
                    this.OverallField = value;
                    this.RaisePropertyChanged("Overall");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Professionalism {
            get {
                return this.ProfessionalismField;
            }
            set {
                if ((this.ProfessionalismField.Equals(value) != true)) {
                    this.ProfessionalismField = value;
                    this.RaisePropertyChanged("Professionalism");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Registration {
            get {
                return this.RegistrationField;
            }
            set {
                if ((this.RegistrationField.Equals(value) != true)) {
                    this.RegistrationField = value;
                    this.RaisePropertyChanged("Registration");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> SatisfactoryArea {
            get {
                return this.SatisfactoryAreaField;
            }
            set {
                if ((this.SatisfactoryAreaField.Equals(value) != true)) {
                    this.SatisfactoryAreaField = value;
                    this.RaisePropertyChanged("SatisfactoryArea");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> StartTime {
            get {
                return this.StartTimeField;
            }
            set {
                if ((this.StartTimeField.Equals(value) != true)) {
                    this.StartTimeField = value;
                    this.RaisePropertyChanged("StartTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> UnsatisfactoryArea {
            get {
                return this.UnsatisfactoryAreaField;
            }
            set {
                if ((this.UnsatisfactoryAreaField.Equals(value) != true)) {
                    this.UnsatisfactoryAreaField = value;
                    this.RaisePropertyChanged("UnsatisfactoryArea");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> WaitTime {
            get {
                return this.WaitTimeField;
            }
            set {
                if ((this.WaitTimeField.Equals(value) != true)) {
                    this.WaitTimeField = value;
                    this.RaisePropertyChanged("WaitTime");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultEntryModel", Namespace="http://schemas.datacontract.org/2004/07/Fot.Admin.Models")]
    [System.SerializableAttribute()]
    public partial class ResultEntryModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AssessmentIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CandidateOptionsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EssayTextField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> SelectedEssayIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> TestScoreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AssessmentId {
            get {
                return this.AssessmentIdField;
            }
            set {
                if ((this.AssessmentIdField.Equals(value) != true)) {
                    this.AssessmentIdField = value;
                    this.RaisePropertyChanged("AssessmentId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CandidateOptions {
            get {
                return this.CandidateOptionsField;
            }
            set {
                if ((object.ReferenceEquals(this.CandidateOptionsField, value) != true)) {
                    this.CandidateOptionsField = value;
                    this.RaisePropertyChanged("CandidateOptions");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EssayText {
            get {
                return this.EssayTextField;
            }
            set {
                if ((object.ReferenceEquals(this.EssayTextField, value) != true)) {
                    this.EssayTextField = value;
                    this.RaisePropertyChanged("EssayText");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> SelectedEssayId {
            get {
                return this.SelectedEssayIdField;
            }
            set {
                if ((this.SelectedEssayIdField.Equals(value) != true)) {
                    this.SelectedEssayIdField = value;
                    this.RaisePropertyChanged("SelectedEssayId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> TestScore {
            get {
                return this.TestScoreField;
            }
            set {
                if ((this.TestScoreField.Equals(value) != true)) {
                    this.TestScoreField = value;
                    this.RaisePropertyChanged("TestScore");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PhotoLogModel", Namespace="http://schemas.datacontract.org/2004/07/Fot.Admin.Models")]
    [System.SerializableAttribute()]
    public partial class PhotoLogModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AdminUserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CandidateIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ExpungeDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AdminUserId {
            get {
                return this.AdminUserIdField;
            }
            set {
                if ((this.AdminUserIdField.Equals(value) != true)) {
                    this.AdminUserIdField = value;
                    this.RaisePropertyChanged("AdminUserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CandidateId {
            get {
                return this.CandidateIdField;
            }
            set {
                if ((this.CandidateIdField.Equals(value) != true)) {
                    this.CandidateIdField = value;
                    this.RaisePropertyChanged("CandidateId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ExpungeDate {
            get {
                return this.ExpungeDateField;
            }
            set {
                if ((this.ExpungeDateField.Equals(value) != true)) {
                    this.ExpungeDateField = value;
                    this.RaisePropertyChanged("ExpungeDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PersonnelPhotoUpdateModel", Namespace="http://schemas.datacontract.org/2004/07/Fot.Admin.Models")]
    [System.SerializableAttribute()]
    public partial class PersonnelPhotoUpdateModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsSupportStaffField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PostTestCapturedByAdminIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] PostTestPhotoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PreTestCapturedByAdminIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] PreTestPhotoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime TestDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSupportStaff {
            get {
                return this.IsSupportStaffField;
            }
            set {
                if ((this.IsSupportStaffField.Equals(value) != true)) {
                    this.IsSupportStaffField = value;
                    this.RaisePropertyChanged("IsSupportStaff");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PostTestCapturedByAdminId {
            get {
                return this.PostTestCapturedByAdminIdField;
            }
            set {
                if ((this.PostTestCapturedByAdminIdField.Equals(value) != true)) {
                    this.PostTestCapturedByAdminIdField = value;
                    this.RaisePropertyChanged("PostTestCapturedByAdminId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] PostTestPhoto {
            get {
                return this.PostTestPhotoField;
            }
            set {
                if ((object.ReferenceEquals(this.PostTestPhotoField, value) != true)) {
                    this.PostTestPhotoField = value;
                    this.RaisePropertyChanged("PostTestPhoto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PreTestCapturedByAdminId {
            get {
                return this.PreTestCapturedByAdminIdField;
            }
            set {
                if ((this.PreTestCapturedByAdminIdField.Equals(value) != true)) {
                    this.PreTestCapturedByAdminIdField = value;
                    this.RaisePropertyChanged("PreTestCapturedByAdminId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] PreTestPhoto {
            get {
                return this.PreTestPhotoField;
            }
            set {
                if ((object.ReferenceEquals(this.PreTestPhotoField, value) != true)) {
                    this.PreTestPhotoField = value;
                    this.RaisePropertyChanged("PreTestPhoto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime TestDate {
            get {
                return this.TestDateField;
            }
            set {
                if ((this.TestDateField.Equals(value) != true)) {
                    this.TestDateField = value;
                    this.RaisePropertyChanged("TestDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="", ConfigurationName="FotService.FotService")]
    public interface FotService {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:FotService/GetSchedules", ReplyAction="urn:FotService/GetSchedulesResponse")]
        LanMonitor.FotService.SchedulePackage GetSchedules(string username, string password, string hash);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:FotService/GetSchedules", ReplyAction="urn:FotService/GetSchedulesResponse")]
        System.Threading.Tasks.Task<LanMonitor.FotService.SchedulePackage> GetSchedulesAsync(string username, string password, string hash);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:FotService/GetAssessmentPackage", ReplyAction="urn:FotService/GetAssessmentPackageResponse")]
        LanMonitor.FotService.BundlePackage GetAssessmentPackage(string username, string password, int BundleId);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:FotService/GetAssessmentPackage", ReplyAction="urn:FotService/GetAssessmentPackageResponse")]
        System.Threading.Tasks.Task<LanMonitor.FotService.BundlePackage> GetAssessmentPackageAsync(string username, string password, int BundleId);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:FotService/GetRequiredAssessments", ReplyAction="urn:FotService/GetRequiredAssessmentsResponse")]
        System.Collections.Generic.List<LanMonitor.FotService.AssessmentBundleViewModel> GetRequiredAssessments(int CenterId);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:FotService/GetRequiredAssessments", ReplyAction="urn:FotService/GetRequiredAssessmentsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<LanMonitor.FotService.AssessmentBundleViewModel>> GetRequiredAssessmentsAsync(int CenterId);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:FotService/ResultUpdate", ReplyAction="urn:FotService/ResultUpdateResponse")]
        bool ResultUpdate(LanMonitor.FotService.ResultUpdateModel result);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:FotService/ResultUpdate", ReplyAction="urn:FotService/ResultUpdateResponse")]
        System.Threading.Tasks.Task<bool> ResultUpdateAsync(LanMonitor.FotService.ResultUpdateModel result);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:FotService/TriggerEndOfDay", ReplyAction="urn:FotService/TriggerEndOfDayResponse")]
        LanMonitor.FotService.SchedulePackage TriggerEndOfDay(string username, string password, System.Collections.Generic.List<LanMonitor.FotService.PhotoLogModel> items);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:FotService/TriggerEndOfDay", ReplyAction="urn:FotService/TriggerEndOfDayResponse")]
        System.Threading.Tasks.Task<LanMonitor.FotService.SchedulePackage> TriggerEndOfDayAsync(string username, string password, System.Collections.Generic.List<LanMonitor.FotService.PhotoLogModel> items);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:FotService/PersonnelPhotoUpdate", ReplyAction="urn:FotService/PersonnelPhotoUpdateResponse")]
        LanMonitor.FotService.SchedulePackage PersonnelPhotoUpdate(string username, string password, System.Collections.Generic.List<LanMonitor.FotService.PersonnelPhotoUpdateModel> staffList);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:FotService/PersonnelPhotoUpdate", ReplyAction="urn:FotService/PersonnelPhotoUpdateResponse")]
        System.Threading.Tasks.Task<LanMonitor.FotService.SchedulePackage> PersonnelPhotoUpdateAsync(string username, string password, System.Collections.Generic.List<LanMonitor.FotService.PersonnelPhotoUpdateModel> staffList);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FotServiceChannel : LanMonitor.FotService.FotService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FotServiceClient : System.ServiceModel.ClientBase<LanMonitor.FotService.FotService>, LanMonitor.FotService.FotService {
        
        public FotServiceClient() {
        }
        
        public FotServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FotServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FotServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FotServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public LanMonitor.FotService.SchedulePackage GetSchedules(string username, string password, string hash) {
            return base.Channel.GetSchedules(username, password, hash);
        }
        
        public System.Threading.Tasks.Task<LanMonitor.FotService.SchedulePackage> GetSchedulesAsync(string username, string password, string hash) {
            return base.Channel.GetSchedulesAsync(username, password, hash);
        }
        
        public LanMonitor.FotService.BundlePackage GetAssessmentPackage(string username, string password, int BundleId) {
            return base.Channel.GetAssessmentPackage(username, password, BundleId);
        }
        
        public System.Threading.Tasks.Task<LanMonitor.FotService.BundlePackage> GetAssessmentPackageAsync(string username, string password, int BundleId) {
            return base.Channel.GetAssessmentPackageAsync(username, password, BundleId);
        }
        
        public System.Collections.Generic.List<LanMonitor.FotService.AssessmentBundleViewModel> GetRequiredAssessments(int CenterId) {
            return base.Channel.GetRequiredAssessments(CenterId);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<LanMonitor.FotService.AssessmentBundleViewModel>> GetRequiredAssessmentsAsync(int CenterId) {
            return base.Channel.GetRequiredAssessmentsAsync(CenterId);
        }
        
        public bool ResultUpdate(LanMonitor.FotService.ResultUpdateModel result) {
            return base.Channel.ResultUpdate(result);
        }
        
        public System.Threading.Tasks.Task<bool> ResultUpdateAsync(LanMonitor.FotService.ResultUpdateModel result) {
            return base.Channel.ResultUpdateAsync(result);
        }
        
        public LanMonitor.FotService.SchedulePackage TriggerEndOfDay(string username, string password, System.Collections.Generic.List<LanMonitor.FotService.PhotoLogModel> items) {
            return base.Channel.TriggerEndOfDay(username, password, items);
        }
        
        public System.Threading.Tasks.Task<LanMonitor.FotService.SchedulePackage> TriggerEndOfDayAsync(string username, string password, System.Collections.Generic.List<LanMonitor.FotService.PhotoLogModel> items) {
            return base.Channel.TriggerEndOfDayAsync(username, password, items);
        }
        
        public LanMonitor.FotService.SchedulePackage PersonnelPhotoUpdate(string username, string password, System.Collections.Generic.List<LanMonitor.FotService.PersonnelPhotoUpdateModel> staffList) {
            return base.Channel.PersonnelPhotoUpdate(username, password, staffList);
        }
        
        public System.Threading.Tasks.Task<LanMonitor.FotService.SchedulePackage> PersonnelPhotoUpdateAsync(string username, string password, System.Collections.Generic.List<LanMonitor.FotService.PersonnelPhotoUpdateModel> staffList) {
            return base.Channel.PersonnelPhotoUpdateAsync(username, password, staffList);
        }
    }
}
