//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuthorApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdminUser
    {
        public AdminUser()
        {
            this.Assessments = new HashSet<Assessment>();
        }
    
        public int AdminId { get; set; }
        public string Username { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public string Password { get; set; }
        public Nullable<System.DateTime> RegDate { get; set; }
        public bool Active { get; set; }
        public bool IsAdmin { get; set; }
    
        public virtual ICollection<Assessment> Assessments { get; set; }
    }
}
