//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuthorApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FotAuthorContext : DbContext
    {
    
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Assessment> Assessments { get; set; }
        public DbSet<AssessmentAnswer> AssessmentAnswers { get; set; }
        public DbSet<AssessmentTopic> AssessmentTopics { get; set; }
        public DbSet<QuestionDifficultyLevel> QuestionDifficultyLevels { get; set; }
        public DbSet<QuestionGroup> QuestionGroups { get; set; }
        public DbSet<AdminUser> AdminUsers { get; set; }
        public DbSet<AssessmentQuestion> AssessmentQuestions { get; set; }
    }
}
