//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fot.Client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CampaignEntry
    {
        public CampaignEntry()
        {
            this.AssessmentResults = new HashSet<AssessmentResult>();
            this.PartnerWalletDebits = new HashSet<PartnerWalletDebit>();
        }
    
        public int EntryId { get; set; }
        public int CampaignId { get; set; }
        public int CandidateId { get; set; }
        public bool Scheduled { get; set; }
        public Nullable<int> SessionId { get; set; }
        public bool Tested { get; set; }
        public Nullable<System.DateTime> DateTested { get; set; }
        public Nullable<bool> PhotoCaptured { get; set; }
        public Nullable<int> PhotoCapturedBy { get; set; }
        public Nullable<System.DateTime> TestStartTime { get; set; }
        public Nullable<System.DateTime> TestEndTime { get; set; }
    
        public virtual ICollection<AssessmentResult> AssessmentResults { get; set; }
        public virtual Campaign Campaign { get; set; }
        public virtual Candidate Candidate { get; set; }
        public virtual CandidateAssessment CandidateAssessment { get; set; }
        public virtual TestSession TestSession { get; set; }
        public virtual ICollection<PartnerWalletDebit> PartnerWalletDebits { get; set; }
        public virtual CandidateScheduleResponse CandidateScheduleResponse { get; set; }
    }
}
