//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fot.Client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Candidate
    {
        public Candidate()
        {
            this.CampaignEntries = new HashSet<CampaignEntry>();
            this.CandidateFeedbacks = new HashSet<CandidateFeedback>();
        }
    
        public int CandidateId { get; set; }
        public string BiometricaID { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string MobileNo { get; set; }
        public string AlternateEmail { get; set; }
        public string AlternateMobileNo { get; set; }
        public System.DateTime DateAdded { get; set; }
        public Nullable<int> LocationId { get; set; }
        public string ClientUniqueID { get; set; }
        public string Email { get; set; }
        public string PhotoFileName { get; set; }
    
        public virtual ICollection<CampaignEntry> CampaignEntries { get; set; }
        public virtual Location Location { get; set; }
        public virtual ICollection<CandidateFeedback> CandidateFeedbacks { get; set; }
    }
}
