//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fot.Client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CandidateScheduleResponse
    {
        public int EntryId { get; set; }
        public bool AcceptSchedule { get; set; }
        public string RejectReason { get; set; }
        public System.DateTime DateResponded { get; set; }
    
        public virtual CampaignEntry CampaignEntry { get; set; }
    }
}
