//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fot.Client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeedbackType
    {
        public FeedbackType()
        {
            this.CandidateFeedbacks = new HashSet<CandidateFeedback>();
        }
    
        public int EntryId { get; set; }
        public string FeedbackReason { get; set; }
    
        public virtual ICollection<CandidateFeedback> CandidateFeedbacks { get; set; }
    }
}
