//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmsSender
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssessmentAnswer
    {
        public int AnswerId { get; set; }
        public int QuestionId { get; set; }
        public string AnswerText { get; set; }
        public byte[] AnswerImage { get; set; }
        public bool IsImage { get; set; }
        public bool IsCorrect { get; set; }
    
        public virtual AssessmentQuestion AssessmentQuestion { get; set; }
    }
}
