//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MessageService
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailQueue
    {
        public int EntryId { get; set; }
        public int BatchId { get; set; }
        public Nullable<int> CampaignEntryId { get; set; }
        public string EmailTo { get; set; }
        public Nullable<System.DateTime> DateTimeQueued { get; set; }
        public Nullable<System.DateTime> DateTimeSent { get; set; }
        public bool Sent { get; set; }
    
        public virtual CampaignEntry CampaignEntry { get; set; }
        public virtual EmailBatch EmailBatch { get; set; }
    }
}
