//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fot.Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccessLog
    {
        public int EntryId { get; set; }
        public Nullable<int> AdminId { get; set; }
        public string LogEntryType { get; set; }
        public string LogEntryDetails { get; set; }
        public Nullable<System.DateTime> LogDate { get; set; }
        public string IpAddress { get; set; }
        public string UserAgent { get; set; }
    
        public virtual AdminUser AdminUser { get; set; }
    }
}
