//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fot.Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdminUser
    {
        public AdminUser()
        {
            this.AuthorAssignedAssessments = new HashSet<AuthorAssignedAssessment>();
            this.PartnerWalletEntries = new HashSet<PartnerWalletEntry>();
            this.AccessLogs = new HashSet<AccessLog>();
            this.CampaignEntries = new HashSet<CampaignEntry>();
            this.TestDayPhotoes = new HashSet<TestDayPhoto>();
            this.TestDayPhotoes1 = new HashSet<TestDayPhoto>();
            this.TestDayPhotoes2 = new HashSet<TestDayPhoto>();
            this.PhotoLogs = new HashSet<PhotoLog>();
        }
    
        public int AdminId { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public string MobileNo { get; set; }
        public bool Active { get; set; }
        public Nullable<System.DateTime> LastLoginDate { get; set; }
        public bool IsGlobalAdmin { get; set; }
        public bool CanAuthor { get; set; }
        public bool CanSchedule { get; set; }
        public bool HasResultsAccess { get; set; }
        public bool HasFinancialsAccess { get; set; }
        public bool HasUsersAccess { get; set; }
        public bool IsPartnerAdmin { get; set; }
        public bool IsCenterAdmin { get; set; }
        public Nullable<int> PartnerId { get; set; }
        public Nullable<int> CenterId { get; set; }
        public bool HasPartnerUsersAccess { get; set; }
        public bool HasCenterUsersAccess { get; set; }
        public Nullable<System.DateTime> LastPasswordChangedDate { get; set; }
        public int FailedLoginAttempts { get; set; }
        public bool IsCaptureAdmin { get; set; }
    
        public virtual Center Center { get; set; }
        public virtual Partner Partner { get; set; }
        public virtual ICollection<AuthorAssignedAssessment> AuthorAssignedAssessments { get; set; }
        public virtual ICollection<PartnerWalletEntry> PartnerWalletEntries { get; set; }
        public virtual ICollection<AccessLog> AccessLogs { get; set; }
        public virtual ICollection<CampaignEntry> CampaignEntries { get; set; }
        public virtual ICollection<TestDayPhoto> TestDayPhotoes { get; set; }
        public virtual ICollection<TestDayPhoto> TestDayPhotoes1 { get; set; }
        public virtual ICollection<TestDayPhoto> TestDayPhotoes2 { get; set; }
        public virtual ICollection<PhotoLog> PhotoLogs { get; set; }
    }
}
