//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fot.Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CandidateFeedback
    {
        public int EntryId { get; set; }
        public Nullable<int> CandidateId { get; set; }
        public Nullable<int> FeedBackTypeId { get; set; }
        public string FeedbackOther { get; set; }
        public string FeedbackMessage { get; set; }
        public Nullable<System.DateTime> DateSent { get; set; }
    
        public virtual FeedbackType FeedbackType { get; set; }
        public virtual Candidate Candidate { get; set; }
    }
}
