//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fot.Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CandidateAssessment
    {
        public int CampaignEntryId { get; set; }
        public string CandidateGuid { get; set; }
        public byte[] AssessmentData { get; set; }
        public byte[] CurrentAssessmentState { get; set; }
        public int SaveCount { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
    
        public virtual CampaignEntry CampaignEntry { get; set; }
    }
}
