//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fot.Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CenterUser
    {
        public CenterUser()
        {
            this.TestDayPhotoes = new HashSet<TestDayPhoto>();
        }
    
        public int UserId { get; set; }
        public int CenterId { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public string Email { get; set; }
        public string MobileNo { get; set; }
        public System.DateTime DateAdded { get; set; }
        public bool Active { get; set; }
    
        public virtual Center Center { get; set; }
        public virtual ICollection<TestDayPhoto> TestDayPhotoes { get; set; }
    }
}
