//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fot.Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EssayTopic
    {
        public EssayTopic()
        {
            this.AssessmentResults = new HashSet<AssessmentResult>();
        }
    
        public int EssayId { get; set; }
        public Nullable<int> AssessmentId { get; set; }
        public string Topic { get; set; }
    
        public virtual Assessment Assessment { get; set; }
        public virtual ICollection<AssessmentResult> AssessmentResults { get; set; }
    }
}
