//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fot.Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Location
    {
        public Location()
        {
            this.Centers = new HashSet<Center>();
            this.MappedLocations = new HashSet<Location>();
            this.Candidates = new HashSet<Candidate>();
        }
    
        public int LocationId { get; set; }
        public string LocationName { get; set; }
        public Nullable<int> MappedToLocation { get; set; }
    
        public virtual ICollection<Center> Centers { get; set; }
        public virtual ICollection<Location> MappedLocations { get; set; }
        public virtual Location ParentLocation { get; set; }
        public virtual ICollection<Candidate> Candidates { get; set; }
    }
}
