//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fot.Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MessageBatch
    {
        public MessageBatch()
        {
            this.MessageQueues = new HashSet<MessageQueue>();
        }
    
        public int BatchId { get; set; }
        public Nullable<System.DateTime> BatchDate { get; set; }
        public Nullable<int> MessageType { get; set; }
        public string MessageFrom { get; set; }
        public string Message { get; set; }
    
        public virtual ICollection<MessageQueue> MessageQueues { get; set; }
    }
}
