//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fot.Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartnerAssignedCenter
    {
        public int EntryId { get; set; }
        public Nullable<int> CenterId { get; set; }
        public Nullable<int> PartnerId { get; set; }
    
        public virtual Center Center { get; set; }
        public virtual Partner Partner { get; set; }
    }
}
