//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fot.Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartnerWalletEntry
    {
        public int EntryId { get; set; }
        public int PartnerId { get; set; }
        public decimal Amount { get; set; }
        public string Reference { get; set; }
        public System.DateTime EntryDate { get; set; }
        public int EntryAdmin { get; set; }
    
        public virtual AdminUser AdminUser { get; set; }
        public virtual Partner Partner { get; set; }
    }
}
