//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fot.Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShownQuestion
    {
        public ShownQuestion()
        {
            this.ChosenOptions = new HashSet<ChosenOption>();
        }
    
        public int EntryId { get; set; }
        public Nullable<int> CampaignEntryId { get; set; }
        public Nullable<int> QuestionId { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public Nullable<int> CampaignId { get; set; }
        public Nullable<bool> Correct { get; set; }
    
        public virtual ICollection<ChosenOption> ChosenOptions { get; set; }
    }
}
