//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fot.Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestDayPhoto
    {
        public int EntryId { get; set; }
        public Nullable<int> AdminId { get; set; }
        public Nullable<int> CenterUserId { get; set; }
        public Nullable<System.DateTime> TestDate { get; set; }
        public string PreTestPhotoFileName { get; set; }
        public string PostTestPhotoFileName { get; set; }
        public Nullable<int> PreTestCapturedByAdminId { get; set; }
        public Nullable<int> PostTestCapturedByAdminId { get; set; }
    
        public virtual AdminUser AdminUser { get; set; }
        public virtual AdminUser PostTestCaptureAdmin { get; set; }
        public virtual AdminUser PreTestCaptureAdmin { get; set; }
        public virtual CenterUser CenterUser { get; set; }
    }
}
