//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmailSender
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssessmentOutputConfig
    {
        public int ConfigId { get; set; }
        public int AssessmentId { get; set; }
        public Nullable<int> TopicId { get; set; }
        public Nullable<int> DifficultyLevel { get; set; }
        public int NumQuestions { get; set; }
    
        public virtual Assessment Assessment { get; set; }
        public virtual AssessmentTopic AssessmentTopic { get; set; }
        public virtual QuestionDifficultyLevel QuestionDifficultyLevel { get; set; }
    }
}
