//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fot.Lan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdminUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AdminUser()
        {
            this.PostTestCapturedAdmins = new HashSet<AdminUser>();
            this.PreTestCapturedAdmins = new HashSet<AdminUser>();
            this.Candidates = new HashSet<Candidate>();
        }
    
        public int AdminId { get; set; }
        public int ActualUserId { get; set; }
        public bool IsCaptureAdmin { get; set; }
        public bool IsSupportStaff { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public System.DateTime DownloadDate { get; set; }
        public byte[] PreTestPhoto { get; set; }
        public byte[] PostTestPhoto { get; set; }
        public bool Synchronized { get; set; }
        public Nullable<int> PreTestCapturedByAdminId { get; set; }
        public Nullable<int> PostTestCapturedByAdminId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdminUser> PostTestCapturedAdmins { get; set; }
        public virtual AdminUser PostTestCaptureAdmin { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdminUser> PreTestCapturedAdmins { get; set; }
        public virtual AdminUser PreTestCaptureAdmin { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Candidate> Candidates { get; set; }
    }
}
