//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fot.Lan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssessmentPackage
    {
        public int EntryId { get; set; }
        public int BundleId { get; set; }
        public string BundleName { get; set; }
        public byte[] BundleData { get; set; }
        public Nullable<System.DateTime> DownloadDate { get; set; }
    }
}
