//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fot.Lan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssessmentResult
    {
        public int EntryId { get; set; }
        public int CandidateEntryId { get; set; }
        public int AssessmentId { get; set; }
        public string Score { get; set; }
        public string CandidateOptions { get; set; }
        public Nullable<int> SelectedEssayId { get; set; }
        public string EssayText { get; set; }
    
        public virtual Candidate Candidate { get; set; }
    }
}
