//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fot.Lan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Candidate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Candidate()
        {
            this.AssessmentResults = new HashSet<AssessmentResult>();
        }
    
        public int CandidateEntryId { get; set; }
        public string CandidateGuid { get; set; }
        public int CandidateId { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public string MobileNo { get; set; }
        public byte[] CandidatePhoto { get; set; }
        public int BundleId { get; set; }
        public int CampaignId { get; set; }
        public bool ShowFeedback { get; set; }
        public int SessionId { get; set; }
        public bool AssessmentStarted { get; set; }
        public Nullable<System.DateTime> DateTimeStarted { get; set; }
        public bool AssessmentCompleted { get; set; }
        public Nullable<System.DateTime> DateTimeCompleted { get; set; }
        public bool Synchronized { get; set; }
        public Nullable<System.DateTime> DownloadDate { get; set; }
        public Nullable<int> PhotoCapturedByAdminId { get; set; }
    
        public virtual AdminUser AdminUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssessmentResult> AssessmentResults { get; set; }
        public virtual CandidateAssessment CandidateAssessment { get; set; }
        public virtual TestFeedback TestFeedback { get; set; }
    }
}
